### ISSUE TITLE
Fix NNExtractor and RasterGrid class interdependency

### ISSUE THREAD

**Issue by pasquierjb** [WFP-VAM/HRM#12]
NNExtractor needs GRID.download_images to be run previously otherwise GRID.image_dir=None

network = NNExtractor(id, sat, GRID.image_dir, network_model, step, GRID)

**Comment by lorenzori** [comment]
one way we could go around this is to create a dictionary that maps coordinates to grid points and write that to disk.

**Comment by lorenzori** [comment]
done with PR #27
