### ISSUE TITLE
NNExtractor scores all images in the folder

### ISSUE THREAD

**Issue by lorenzori** [WFP-VAM/HRM#3]
we should make it feasible to score only a subset of images, for example in a production environment to score only relevant pictures.

**Comment by lorenzori** [comment]
something like we did in the _average_feature_dir:

```
i = int(name[0: 5]) + a
j = int(name[6:10]) + b
img_path = os.path.join(image_dir, name, str(i)+'_'+str(j)+".jpg")
```

**Comment by lorenzori** [comment]
we could always put the logic outside, i.e. specify a different directory or loop over directories of images to process...

**Comment by pasquierjb** [comment]
extract_features now takes list_i,list_j as input
